modLoader = "javafml"
loaderVersion = "[2,]"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "icon.png"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
required = true
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
required = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"