modLoader = "javafml"
loaderVersion = "[2,]"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.compat.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "iris"
type = "optional"
ordering = "AFTER"
side = "CLIENT"